# Generated by Django 5.1.6 on 2025-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bandteam_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandteam',
            name='image',
            field=models.ImageField(default=1, upload_to='bands/'),
            preserve_default=False,
        ),
    ]
