# Generated by Django 5.1.6 on 2025-02-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
