# Generated by Django 5.1.6 on 2025-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandteam',
            name='booking_fee',
            field=models.IntegerField(default=0),
        ),
    ]
