# Generated by Django 5.1.7 on 2025-04-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_product_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
