# Generated by Django 5.1.7 on 2025-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_staf_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staf',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
