# Generated by Django 5.1.5 on 2025-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
