# Generated by Django 5.1.5 on 2025-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
