# Generated by Django 5.1.5 on 2025-01-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0004_customuser_location_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="compatibility",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="installation_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="power_rating",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
