# Generated by Django 5.1.5 on 2025-01-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0005_product_compatibility_product_dimensions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pincode",
            field=models.CharField(
                blank=True, default="683511", max_length=6, null=True
            ),
        ),
    ]
